
default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: subway_review_site_development

test:
  <<: *default
  database: subway_review_site_test

production:
  <<: *default
  database: subway_review_site_production
  username: subway_review_site
  password: <%= ENV['SUBWAY_REVIEW_SITE_DATABASE_PASSWORD'] %>
